feat(pre-commit): add pre-commit checks

diff --git a/harness b/harness
--- a/harness
+++ b/harness
@@ -41,14 +41,16 @@ down() {
 
 format() {
   echo '░░░ Running `crystal tool format` over `drivers` and `repositories`'
+  exit_code=0
   docker-compose run \
                      -v ./drivers:/wd/drivers \
                      -v ./repositories:/wd/repositories \
                      --no-deps \
                      --rm \
                      install-shards \
-                     crystal tool format
+                     crystal tool format $@ || exit_code=$?
   say_done
+  exit ${exit_code}
 }
 
 report() {
@@ -61,7 +63,8 @@ report() {
   # Ensure shards are satisfied before running the report
   docker-compose run \
                      --rm \
-                     install-shards &> /dev/null
+                     install-shards # &> /dev/null
+                     # --no-deps \
 
   echo '░░░ Starting environment...'
   docker-compose up -d &> /dev/null
@@ -90,10 +93,18 @@ Command:
 EOF
 }
 
-if [ $# -eq 0 ]
+# Check the number of arguments passed.
+if [[ "$#" -eq 0 ]]
 then
   usage
   exit 1
+fi
+
+# Check if able to connect to docker
+if [[ "$(docker ps &> /dev/null; echo $?)" -eq 1 ]]
+then
+  echo "░░░ Failed to connect to docker. Is it running?"
+  exit 2
 fi
 
 command="$1"
@@ -109,7 +120,7 @@ case $command in
     down
     ;;
   format)
-    format
+    format $@
     ;;
   -h|--help|help)
     usage
